version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: meu_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: meu_banco
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d

  minio:
    image: minio/minio
    container_name: meu_minio
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    ports:
      - "9000:9000"
      - "9090:9090"
    command: server /data --console-address ":9090"
    volumes:
      - minio_data:/data

  minio-init:
    image: minio/mc
    container_name: minio_init
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
        sleep 10;
        mc alias set myminio http://minio:9000 admin admin123;
        mc mb -p myminio/fotos || echo 'Bucket fotos jรก existe';
      "

  api:
    build:
      context: ./apiServidores
    container_name: app_servidores
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - minio
      - minio-init
    environment:
      - SPRING_PROFILES_ACTIVE=docker

volumes:
  postgres_data:
  minio_data:
